version: '3'

services:
  db:
    image: mongo
    ports:
      - '27017:27017'
#    volumes:
#      - .  /data/db
  web:
    build: ./app
    command: npm start
    ports:
      - '3000:3000'
    depends_on:
      - db